@startuml
skinparam componentStyle uml2

node IED as ied
node RabbitMQ as mq
component rcb_sub as rcbsub #Yellow
component jansson as jansson
component libiec61850 as libiec
component [rabbitmq-c] as mqc
component Argp as argp

() "MMS" as mmsif
() "API" as libiecif
() "API" as mqcif
() "JSON API" as jsonif
() "Parametri API" as argpif
() "TCP/IP" as amqpif

ied -u- mmsif : IEC 61850
mq -u- amqpif : AMQP
jansson -- jsonif
libiec -r- libiecif
mqc -l- mqcif
argp -u- argpif

libiec -d-> mmsif
mqc -d-> amqpif
rcbsub .u.> jsonif : käyttää
rcbsub .l.> libiecif : käyttää
rcbsub .d.> argpif : käyttää
rcbsub .r.> mqcif : käyttää

note top of jansson
	Kirjasto JSON-rakenteen lukuun
	ja rakentamiseen
end note

note bottom of argp
	Kirjasto komentoriviparametrien
	lukuun ja määrittämiseen
end note

note top of mqc
	kirjasto, joka abstrahoi
	AMQP-pohjaisen kommunikoinnin
	TCP/IP:n yli
end note

note top of libiec
	Kirjasto, joka abstrahoi IEC 61850
	-standardin MMS-protokollan yli
end note
@enduml
